export type AppView =
  | 'login'
  | 'dashboard'
  | 'holdings'
  | 'trades'
  | 'ask-finor'
  | 'exit-strategy'
  | 'insights'
  | 'target'
  | 'sell-planner'
  | 'transactions'
  | 'finance'
  | 'pnl'
  | 'help'
  | 'settings'
  | 'admin';
